# This is a basic workflow to help you get started with Actions
name: CI LIVE EU

on:
  push:
    tags:
      - "EU.*"
jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     